### ISSUE TITLE
Dump1090 option --quiet

### ISSUE THREAD

**Issue by ipl2004** [kosho/flight-track#1]
Hi Kosho,

I was wondering why the latest Dump1090 does not support the --quiet option that seems to be needed to run with the ELK. 

Has anyone else had success with ELK and ADS-B?

**Comment by kosho** [comment]
Hi @ipl2004, if you want to retrieve the data in JSON format which Logstash requires, you need to request to `/data.json`. In [dump1090.c](https://github.com/antirez/dump1090/blob/master/dump1090.c), around line 2226,

```
    /* Select the content to send, we have just two so far:
     * "/" -> Our google map application.
     * "/data.json" -> Our ajax request to update planes. */
```

, otherwise, you will get the data in HTML.

My dump1090 has been working in these several months at home with Logstash. You may try like below in order to make sure you can really get the updates in JSON format.

```sh
$ curl http://localhost:8080/data.json
[
{"hex":"abb325", "squawk":"0000", "flight":"PAC213  ", "lat":35.310198, "lon":139.507784, "validposition":1, "altitude":28200,  "vert_rate":2176,"track":261, "validtrack":1,"speed":433, "messages":240, "seen":207}
]
```

The `--quiet` option isn't necessary. If you don't want to mess your terminal, you can type just:

```
$ dump1090 --net --aggressive > /dev/null &
```

Hope it helps!

**Comment by ipl2004** [comment]
Many thanks for your help Kosho

Is this simply a parameter I pass along with the ./dump1090 —net —aggressive command or am I expected to change to code and recompile?

I am sorry, I am not completely sure what to do.

Ian

**Comment by ipl2004** [comment]
Hi, 
I have worked i out. It’s the cURL request that need to have the /data.json request. Sorry for being slow today.

Ian
